-- CREATE USER IF NOT EXISTS counter WITH PASSWORD 'counter';
-- CREATE DATABASE IF NOT EXISTS counters OWNER counter;
-- \connect counters;
-- CREATE SCHEMA IF NOT EXISTS AUTHORIZATION counter;
CREATE SCHEMA AUTHORIZATION counter;